"""Conformance tests: real PostgreSQL semantics through the proxy."""

from __future__ import annotations

from collections.abc import Iterator
from datetime import timedelta

import pytest
from psycopg.types.json import Jsonb

from pytest_pglite import PGliteConfig, PGliteServer

psycopg = pytest.importorskip("psycopg")

pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def server() -> Iterator[PGliteServer]:
    with PGliteServer(PGliteConfig()) as running:
        yield running


@pytest.fixture
def conn(server: PGliteServer) -> Iterator[object]:
    with psycopg.connect(server.dsn) as connection:
        yield connection


def test_rich_types(conn: object) -> None:
    conn.execute(
        "create table typed ("
        "  id bigint generated by default as identity primary key,"
        "  flag boolean,"
        "  price numeric(10, 2),"
        "  payload jsonb,"
        "  tags text[],"
        "  blob bytea,"
        "  created timestamptz,"
        "  span interval,"
        "  uid uuid"
        ")"
    )
    conn.execute(
        "insert into typed (flag, price, payload, tags, blob, created, span, uid)"
        " values (%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            True,
            "12.34",
            Jsonb({"a": [1, 2]}),
            ["x", "y"],
            b"\x00\x01",
            "2026-01-02T03:04:05+00:00",
            "1 day 02:03:00",
            "11111111-2222-3333-4444-555555555555",
        ),
    )
    row = conn.execute(
        "select flag, price, payload->'a'->>1, tags[1], blob, span, uid from typed"
    ).fetchone()
    assert row[0] is True
    assert str(row[1]) == "12.34"
    assert row[2] == "2"
    assert row[3] == "x"
    assert row[4] == b"\x00\x01"
    assert row[5] == timedelta(days=1, hours=2, minutes=3)
    assert str(row[6]) == "11111111-2222-3333-4444-555555555555"
    conn.rollback()


def test_cursors(conn: object) -> None:
    conn.execute("create table cursor_demo (n int)")
    conn.execute("insert into cursor_demo select generate_series(1, 10)")
    conn.commit()
    conn.execute("declare c cursor for select n from cursor_demo order by n")
    rows = conn.execute("fetch 3 from c").fetchall()
    assert rows == [(1,), (2,), (3,)]
    conn.execute("close c")
    conn.rollback()


def test_large_result_overflows_cma(conn: object) -> None:
    # The reply buffer is a few megabytes; a large result spills to the socket
    # file path inside the preopened filesystem, which the engine must drain.
    row = conn.execute(
        "select count(*), sum(n) from (select generate_series(1, 400000) as n) s"
    ).fetchone()
    assert row == (400000, 80000200000)
    conn.rollback()


def test_copy_to_stdout(conn: object) -> None:
    conn.execute("create table copy_out (id int, name text)")
    conn.execute(
        "insert into copy_out select n, 'row-' || n from generate_series(1, 500) n"
    )
    conn.commit()
    with conn.cursor().copy("copy copy_out to stdout") as copy:
        rows = list(copy.rows())
    # COPY TO STDOUT is textual; values arrive as strings.
    assert rows[0] == ("1", "row-1")
    assert len(rows) == 500
    conn.rollback()


def test_copy_from_stdin_is_reported_cleanly(conn: object) -> None:
    # The libpglite CMA transport cannot stream CopyData into a synchronous
    # CopyFrom; the proxy answers 0A000 instead of wedging the backend.
    conn.execute("create table copy_in (id int, name text)")
    conn.commit()
    with pytest.raises(psycopg.errors.FeatureNotSupported) as excinfo:
        with conn.cursor().copy("copy copy_in from stdin") as copy:
            copy.write_row((1, "a"))
    assert excinfo.value.sqlstate == "0A000"
    conn.rollback()
    assert conn.execute("select 1 as alive").fetchone() == (1,)
    conn.rollback()


def test_multiple_statements_simple_query(conn: object) -> None:
    conn.execute("create table multi_a (n int); create table multi_b (n int)")
    conn.rollback()


def test_error_sqlstates(conn: object) -> None:
    conn.execute(
        "create table errors (id int primary key, tag text not null check (tag <> ''))"
    )
    conn.execute("insert into errors values (1, 'ok')")
    conn.commit()

    cases: list[tuple[str, tuple[object, ...], str]] = [
        ("insert into errors values (1, 'dup')", (), "23505"),
        ("insert into errors values (2, null)", (), "23502"),
        ("insert into errors values (3, '')", (), "23514"),
        ("select 1/0", (), "22012"),
        ("select * from missing", (), "42P01"),
        ("syntax error here", (), "42601"),
        ("insert into errors values ('not-an-int', 'x')", (), "22P02"),
    ]
    for sql, params, expected in cases:
        with pytest.raises(psycopg.Error) as excinfo:
            conn.execute(sql, params or None)
        assert excinfo.value.sqlstate == expected, sql
        conn.rollback()
        assert conn.execute("select 1 as alive").fetchone() == (1,)
        conn.rollback()


def test_sequences_and_temp_tables(conn: object) -> None:
    conn.execute("create sequence seq_test start 42")
    assert conn.execute("select nextval('seq_test')").fetchone() == (42,)
    assert conn.execute("select nextval('seq_test')").fetchone() == (43,)
    conn.execute("create temp table tmp_local (n int)")
    conn.execute("insert into tmp_local values (1)")
    assert conn.execute("select count(*) from tmp_local").fetchone() == (1,)
    conn.rollback()


def test_catalog_queries(conn: object) -> None:
    row = conn.execute(
        "select current_schema(), current_user, version() like 'PostgreSQL 17%'"
    ).fetchone()
    assert row[0] == "public"
    assert row[1] == "postgres"
    assert row[2] is True
    assert conn.execute(
        "select count(*) > 0 from pg_catalog.pg_tables where schemaname = 'pg_catalog'"
    ).fetchone() == (True,)
    conn.rollback()


def test_prepared_statement_reuse(conn: object) -> None:
    cursor = conn.cursor()
    for value in range(10):
        cursor.execute("select %s::int * 3 as n", (value,), prepare=True)
        assert cursor.fetchone() == (value * 3,)
    conn.rollback()


def test_two_connections_transaction_pinning(server: PGliteServer) -> None:
    import threading
    import time

    with psycopg.connect(server.dsn) as first, psycopg.connect(server.dsn) as second:
        first.execute("create table pinned (n int)")
        first.commit()
        # Leave an open transaction on the first connection: it now owns the
        # single backend until commit or rollback.
        first.execute("insert into pinned values (1)")

        outcome: dict[str, str] = {}

        def writer() -> None:
            try:
                second.execute("insert into pinned values (2)")
                second.commit()
                outcome["result"] = "ok"
            except Exception as exc:  # noqa: BLE001
                outcome["result"] = repr(exc)

        thread = threading.Thread(target=writer)
        thread.start()
        time.sleep(0.2)
        # Nothing else may run until the first connection ends its transaction.
        assert outcome == {}
        first.commit()
        thread.join(timeout=15)
        assert outcome.get("result") == "ok"
        assert first.execute("select count(*) from pinned").fetchone() == (2,)
        first.rollback()


def test_generated_columns_and_views(conn: object) -> None:
    conn.execute(
        "create table gen (a int, b int, total int generated always as (a + b) stored)"
    )
    conn.execute("insert into gen (a, b) values (2, 3)")
    conn.execute("create view gen_view as select a, total from gen")
    assert conn.execute("select total from gen_view").fetchone() == (5,)
    conn.rollback()


def test_create_index_concurrently_if_not_exists(server: PGliteServer) -> None:
    """An ``IF NOT EXISTS`` concurrent statement stays a no-op.

    The proxy rewrites CONCURRENTLY away for the single-backend build
    (PGlite #901); when the index already exists the plain statement must
    still short-circuit instead of rebuilding it.
    """
    with psycopg.connect(server.dsn, autocommit=True) as conn:
        conn.execute("create table cic_demo (id int, name text)")
        conn.execute("insert into cic_demo values (1, 'a')")
        conn.execute("create index if not exists cic_demo_name_idx on cic_demo (name)")
        conn.execute(
            "create index concurrently if not exists cic_demo_name_idx "
            "on cic_demo (name)"
        )
        row = conn.execute(
            "select indisvalid from pg_index "
            "where indexrelid = 'cic_demo_name_idx'::regclass"
        ).fetchone()
        assert row == (True,)
